apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: node-app1
  namespace: cg-akeyless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
      annotations: 
        akeyless/enabled: "true"
        akeyless/inject_file: "/K8s/app1secret"
    spec:
      containers:
      - name: node-app1
        image: devorbitus/app1
        ports:
        - containerPort: 3000
        # env:
        #   - name: MY_SECRET
        #     value: akeyless:/K8s/app1secret
