apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: app1
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: devorbitus/app1
      custom:
        buildCommand: ./custom-build.sh

deploy:
  kubectl:
    manifests:
    - deployment.yml
    - service.yml
    - ingress.yml
    defaultNamespace: cg-akeyless
